#:kivy 2.0

<MyLayout>
    BoxLayout:
        orientation: "vertical"
        # Widgets expand to the size of our app
        size: root.width, root.width
        padding: 50
        spacing: 20

        # Add image by pointing to the image
        Image:
            source: "Rio.jpg"
            allow_stretch: True
            keep_ratio: True

        Button:
            text: "Submit"
            background_color: (1,0,0,1)
